[package]
name = "pdrs-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdrs-core = { path = "../pdrs-core" }
pdrs-game-macro = { path = "../pdrs-game-macro" }